package com.app.amtadminapp.utils

/**
 * Created by Jimmy
 */
object PrefConstants {

    val PREF_IS_WELCOME = "PREF_IS_WELCOME"
    val PREF_IS_LOGIN = "PREF_IS_LOGIN"
    val PREF_USER_ID = "PREF_USER_ID"
    val PREF_USER_TYPE_ID = "PREF_USER_TYPE_ID"
    val PREF_USER_FIRST_NAME = "PREF_USER_FIRST_NAME"
    val PREF_USER_LAST_NAME = "PREF_USER_LAST_NAME"
    val PREF_USER_EMAIL = "PREF_USER_EMAIL"
    val PREF_USER_MOBILE = "PREF_USER_MOBILE"
    val PREF_USER_IMAGE = "PREF_USER_IMAGE"
    val PREF_USER_NAME = "PREF_USER_NAME"
    val PREF_FullUSER_NAME = "PREF_FullUSER_NAME"

    val PREF_INQUIRY_ID = "PREF_INQUIRY_ID"
    val PREF_STUDENT_INQUIRY_JSON = "PREF_STUDENT_INQUIRY_JSON"
    val UPDATE_PROFILE_EDUCATION = "UPDATE_PROFILE_EDUCATION"
    val UPDATE_PROFILE_EXPERIENCE = "UPDATE_PROFILE_EXPERIENCE"
    val PREF_TOKEN = "PREF_TOKEN"

    val PREF_TOUR_BOOKING_ID = "PREF_TOUR_BOOKING_ID"

    val PREF_ADMIN_CALL = "PREF_ADMIN_CALL"
    val PREF_ADMIN_MAIL = "PREF_ADMIN_MAIL"
}